
services:
  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 5
  app:
    build: ../
    restart: always
    ports:
      - 8080:8080
    environment:
      - DEBUG=false
      - DB=postgresql://postgres:postgres@postgres:5432/app?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
